### ISSUE TITLE
Adding instance fails with fatal error: Call to undefined function PARAM_RAW()

### ISSUE THREAD

**Issue by mudrd8mz** [webtechbilisim/moodle-enrol_paytrpayment#4]
I am unable to add a new instance to a course. It ends with fatal error: Call to undefined function PARAM_RAW()

This is likely because of https://github.com/webtechbilisim/moodle-enrol_paytrpayment/blob/74b9af2f2ff55a8e3592021700e7fda564344380/edit.php#L93

**Comment by webtechbilisim** [comment]
ce82b5d fixed.
